### ISSUE TITLE
Decide on convention and document how to encode protocols into Consul

### ISSUE THREAD

**Issue by FRosner** [FRosner/cluster-broccoli#15]
### Problem

When discovering a service of an instance through Consul, we only get address and port, but not protocol.
### Solution

Right now, we encode the protocol as tags (e.g. `protocol:http`). We should decide whether this is the way to go (esp. because `:` is not supported through the Consul DNS interface and throws warnings) and then document how to do it.

We will go for `protocol-http`.

**Comment by rolandjohann** [comment]
Solution 1)
The service discovery will be done through DNS and delivers IP and port of the service. This will be layer 3 at OSI model. The used protocol will be treated at layers 5+.
Maybe it's suitable to use consul KV for this as it's designed to deliver configurations and we have a configuration purpose here.

ATM I only have HTTP vs HTTPS as conflicting protocols in mind. Maybe it's an edge case of unknown protocols and further don't has to be handled at consul/DNS because the application using that service is aware that that service exist and what that service is so further it has to know whether it has to connect with HTTP or HTTPS.

Solution 2)
Remembered the consul doc paragraph where protocolling has been mentioned
https://www.consul.io/docs/agent/dns.html at "RFC 2782 Lookup". There will be mentioned that it's possible to tag the service with its protocol and query it with the schema "_[service]._[protocol].service[.datacenter][.domain]". So it seems to be a common use case to tag a service with it's protocol but that doesn't solve the problem of how to properly get that protocol at discovery time.
Maybe we should treat an application and it's preferred use of specific protocols as like an application that only can use specific protocols:
- service A has three protocols (X, Y, Z) implemented, but application only has protocol Y implemented and can use it. If service A has only protocol Z implemented the application has to take care that it can use protocol Z so that argument leads to the developers that they have to take care of service protocols, not the service definition itself.

**Comment by FRosner** [comment]
@rmmjohann the discovery is done through the Consul HTTP interface. And this means we are also getting the tags. Discovery through DNS does not work, because it does not return a socket but just an IP address. Am I right?

How should you encode the protocol in tags when using RFC 2782 Lookup? Just plain? So like "http" as a tag?
